<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Workflow.Studio.Core\Workflow.Studio.Core.csproj" />
    <ProjectReference Include="..\SampleSdkNode\SampleSdkNode.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="SampleTextSourceNode.cs" />
  </ItemGroup>
</Project>
