<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Workflow.Studio.Core\Workflow.Studio.Core.csproj" />
    <ProjectReference Include="..\Workflow.Studio.Nodes\Workflow.Studio.Nodes.csproj" />
    <ProjectReference Include="..\Workflow.Studio.Plugins\Workflow.Studio.Plugins.csproj" />
    <ProjectReference Include="..\Workflow.Studio.Workbench\Workflow.Studio.Workbench.csproj" />
  </ItemGroup>

</Project>
